json.id coffee_shop.id
json.name coffee_shop.name
json.city coffee_shop.city
json.state coffee_shop.state
json.address coffee_shop.address
json.number coffee_shop.number
json.logo coffee_shop.logo
json.created_at coffee_shop.created_at
json.updated_at coffee_shop.updated_at
