### Coffee Shops Index
GET http://localhost:3000/coffee_shops.json

### Coffee Shops Show
GET http://localhost:3000/coffee_shops/3.json

### Coffee Shops Create
POST http://localhost:3000/coffee_shops.json
Content-Type: application/json

{
  "name":"test2",
  "city": "test2",
  "state":"test2",
  "address":"test2",
  "logo":"test2.png"
  }

### Delete Coffee Shop
DELETE http://localhost:3000/coffee_shops/5.json

### User Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name":"Kathleen McDonnell",
  "email":"kathleen@test.com",
  "password":"password",
  "password_confirmation":"password"
}

### Delete User
DELETE http://localhost:3000/users/1.json