@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo3LCJleHAiOjE2ODEzMTk1MzF9.MQ9uUkmz_7usMrEkBaTaSQ6jGjf8hvDgVk7xqv4VC6M
### Coffee Shops Index
GET http://localhost:3000/coffee_shops.json
Authorization: Bearer {{jwt}}

### Coffee Shops Show
GET http://localhost:3000/coffee_shops/ChIJS_Xjr6QN3ogRcSjPgfRIeRo.json
Authorization: Bearer {{jwt}}

### User Sign-Up
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name":"Callie2",
  "email":"callie2@test.com",
  "password":"password",
  "password_confirmation":"password",
  "city":"Palm Bay",
  "state":"Florida"
}

### User Update
PATCH http://localhost:3000/users/7.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "picture": "test.jpeg"
}

### Delete User
DELETE http://localhost:3000/users/7.json
Authorization: Bearer {{jwt}}

### Create a Sessions (User Login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "bristol@test.com",
  "password":"password"
}